### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nafiz1001** [nafiz1001/nix-configuration#1]
- [ ] vscode or not
- [ ] emacs-nox vs. emacs vs. emacs-pgtk?
- [ ] terminal emulator?
- [ ] qbittorrent or qbittorrent-nox?
- [ ] enabling syncthing enables in home-manager and enables firewall in nixos
- [ ] neovim defaulteditor if emacs disabled
